version: '3'

services:
  smartbidsuser:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - smartbidsdb

  smartbidsdb:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartbidsDB
      MYSQL_USER: smartbids
      MYSQL_PASSWORD: smartbids